#baseurl: ""
#url: "http://localhost"

baseurl: "/f2024"
url: "https://cmu-ml-graph-2024f.github.io/"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
